// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	packit "github.com/paketo-buildpacks/packit"
	mock "github.com/stretchr/testify/mock"
)

// EntryResolver is an autogenerated mock type for the EntryResolver type
type EntryResolver struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: name, entries, priorites
func (_m *EntryResolver) Resolve(name string, entries []packit.BuildpackPlanEntry, priorites []interface{}) (packit.BuildpackPlanEntry, []packit.BuildpackPlanEntry) {
	ret := _m.Called(name, entries, priorites)

	var r0 packit.BuildpackPlanEntry
	if rf, ok := ret.Get(0).(func(string, []packit.BuildpackPlanEntry, []interface{}) packit.BuildpackPlanEntry); ok {
		r0 = rf(name, entries, priorites)
	} else {
		r0 = ret.Get(0).(packit.BuildpackPlanEntry)
	}

	var r1 []packit.BuildpackPlanEntry
	if rf, ok := ret.Get(1).(func(string, []packit.BuildpackPlanEntry, []interface{}) []packit.BuildpackPlanEntry); ok {
		r1 = rf(name, entries, priorites)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]packit.BuildpackPlanEntry)
		}
	}

	return r0, r1
}
