// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Install provides a mock function with given fields: downloadDir, destDir, version
func (_m *Runner) Install(downloadDir string, destDir string, version string) error {
	ret := _m.Called(downloadDir, destDir, version)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(downloadDir, destDir, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
